language: bash

sudo: required

services:
- docker

env:
  global:
    - secure: "SXfTh+s9BjJGOEgjEnGh1O43Jen4otq7/Me7yhGT2lOtmynPSLrHLyFePNwKDqdOkcMx4JyH1BWgLMaWg85EQAdGNOSTIcp/phk9Rqe4HI8US5c6E2e3P73aRu2Jc0ANqQ9cnc7cOhd3LVEnjSczJqTLVxemHQqb4RZ7Pcaqre0dvEU7i7Fox1Xb3lyY22NHe/PRX0H7C+vlSd49gjoCsyZTbiyLztHawZH9nlcM+eDvVSaZpiNF85zmr35n48ZWfQ2bsyVW/mKcqDY4ZB4rn5aX6W/FD6hBFKk3OytJhIusXo19lcoWcrtaXf1L3dAaWqIqNZ+4Ru1SlLSL4O17wykSROkYFYfROyGtKzuZE3VZV7RXYjNrxvpqTTHq7V3Zl3hUyUgk4gRzUvNyqiQFy8ISveZu22PZM1+28r7zsmUOzS1lArsH2uzcfuaDQn9YZkf4s15gUgjn1qHNFSZKCoBE2YqPEFvIfxOjH+17rNUzVEjWP9jdaGMiWUhReq3K0R99JU43RG6NkLXKddJAZAcNhmW7HOX36LbFh67at0+mwjno49j6PUMbclHxdFLG0bY+ab+G5/raDInvZBATFh1+ENYX0EV5/TusKmJn4GVdA0mpsI6o1vJgkSK74ublikxs7t7/CPXjDpw+RcK/TGqmj7YwsGGQ6VW1mR6CWH4="
    - secure: "OSUWcsNKB6e/IsXOy7WBeKlizPNEwJ0aF7YbK4b9RtO/QMqwGMnvMUwxD1UUQTJeN1hGve2QkpfyKVk3c4UfN9ftlZuT+pLLCmMxfAL0FPpKmsVQm1ENupm17TsqQPBW3KGYorcgSI2+Fa+zwPMFPtX2wJoYGTMg9YIVvQtwyREcONj8bx2FhVzJlwe+fC3XEOvFxfJXwqyOQk47ZaVXlovViCY408tXrtoYbPz+gxbN/7DPvkT/+mU2Ln7ndfz+8wOUgq5N9FGrV2eGPAxu3Zxr8gXGm10j0N4P6brjSaYlTYhS5byQX/sPyIRBg/gZYxHcL6cIrhrE2uBj+V8wsY6NJ4fhiGicII952ApAOq5RFq+HExGsEYSO/0gf/9AswBJQcYmBo2UBQzO7jmbk0CVTtd6SvE5pUDHUfHSHCaMdTdFjK+6jjvorj9uMQGE9rtpCxlrQGwBTlAppk0NGlrK4Ee5XhEx9NlMMJutLXtEURX7V+poXXdGcxM2H+dxPTe5onTju1gHJR0h1OKdK0D6lS+3ko0tIEY80GitI8tlLY9079MVRy/dBnuTu4tzTCu61Z7+/CmsATFhynTnvNYYBIT1ZdnRomMtz4Co8BEIhOeLhsnUFhsueIiYSuGOvOiTPEsAh/21aSduJZuI50GgooIMr264tdsa4+nJC1h4="
    - secure: "NtrXn3Z7p/RhYEn0HTs5LSnIr/sx9k9o78u0joxJtqndwehWA5z/lOSaelI66q2uybaa66jDL2lFHJue8IExAuX0zOaF44fZnC8LXIjZsZktwd8bIVJoW+79sjeBI+ZsO4nYj1JfIrIG2Bzbo46kgayYovv0G1RGfnCq8Osu3HzLwg5uVbXjnJLZcevo/+KbA006yDiPfnF5kkE+b5xwgZGFw6Q0LfOfZXImGV+uLnQdQSx59PedmnO/4JdUX2llgTr0vZITXpZYZjl3iYLpHHFW/orp8SxMBSM2fEsyD9/yDN79nhvYsFLVGxflQAuo+F9hyYvu9wDT7HTAL84rJ1qaWRy7UzrIhNazUwBHndeaI94tJ2We+bPS5Nwz+ojqlm32RhNYcakIB6elvnXhmFqEaq/cGpcS29P2WE7sRPkDnzvayXMFSbc2TPMQrzRj8guWjfGDsiOfqanrdcNce84EW10uBoP3h8Hwp18haI2SGPF/V29qrnHGveVz0ciMnAF5sPsHjnvMvZrurDM4ahjcqQR0dAxrEiihL95+rXB8VSosuzqZd6khMNRwJ1ZuXm8yprV6ty1K0NuHmdUKEm0Bj8HxukkRsCUJz8ZX42uKe9gSXt5QE5puhIg+LiwpOM6bMumbybSgf0Xcy2SKK2o66ZGC00+kxNoJXvU/hvE="
    - PROJECT="jenkins"
    - REPOSITORY="encodeering"
    - BRANCH="$TRAVIS_BRANCH"
    - COMMIT="32eefe640639cc37b17049351065c2d007a2173c"
  matrix:
    - BASE=debian ARCH=amd64 JAVA=8-jdk-debian-oracle  VERSION=2.89 VERSIONPIN=2.89.2 VARIANT=oracle  SHA=014f669f32bc6e925e926e260503670b32662f006799b133a031a70a794c8a14
    - BASE=debian ARCH=amd64 JAVA=8-jdk-debian-openjdk VERSION=2.89 VERSIONPIN=2.89.2 VARIANT=openjdk SHA=014f669f32bc6e925e926e260503670b32662f006799b133a031a70a794c8a14
    - BASE=alpine ARCH=amd64 JAVA=8-jdk-alpine-openjdk VERSION=2.89 VERSIONPIN=2.89.2 VARIANT=openjdk SHA=014f669f32bc6e925e926e260503670b32662f006799b133a031a70a794c8a14
    - BASE=debian ARCH=amd64 JAVA=8-jdk-debian-oracle  VERSION=0.1                    VARIANT=walle-oracle
    - BASE=debian ARCH=amd64 JAVA=8-jdk-debian-openjdk VERSION=0.1                    VARIANT=walle-openjdk
    - BASE=debian ARCH=armhf JAVA=8-jdk-debian-oracle  VERSION=2.89 VERSIONPIN=2.89.2 VARIANT=oracle  SHA=014f669f32bc6e925e926e260503670b32662f006799b133a031a70a794c8a14
    - BASE=debian ARCH=armhf JAVA=8-jdk-debian-openjdk VERSION=2.89 VERSIONPIN=2.89.2 VARIANT=openjdk SHA=014f669f32bc6e925e926e260503670b32662f006799b133a031a70a794c8a14
    - BASE=debian ARCH=armhf JAVA=8-jdk-debian-oracle  VERSION=0.1                    VARIANT=walle-oracle
    - BASE=debian ARCH=armhf JAVA=8-jdk-debian-openjdk VERSION=0.1                    VARIANT=walle-openjdk

install:
- bash <(curl https://raw.githubusercontent.com/encodeering/docker-ci/master/install.sh) 0.1.5

before_script:
- sudo -E bash ./module.sh "." "./setup.sh" "https://github.com/jenkinsci/docker.git" "modules/$PROJECT" "$COMMIT"

script:
- sudo -E bash ./module.sh "modules" "./build.sh"

after_script:
- docker images

deploy:
  script: sudo -E bash ./module.sh "." "./release.sh"
  provider: script
  skip_cleanup: true
  on:
    all_branches: true
